var resultPlayerList = ["Eadie Barrie","Billy Brooks","Rodger Burcham","Rodger Burcham #2","Rodger Burcham #3","Eric Eickhoff","Earl Grant","Erin Grant","Kevin Hohnbaum","Anita Hopper","Jeanne Mannella","Jeanne Mannella #2","Joseph Mccoy","Bryan Povlinski","Kevin Sobiski","Kevin Sobiski #2"]
var listOfTeams = ["No Pick","Kentucky","MVSU/WKU","Iowa St","Connecticut","Wichita St","VCU","Indiana","New Mexico St","UNLV","Colorado","Baylor","S Dakota St","Notre Dame","Xavier","Duke","Lehigh","Michigan St","LIU","Memphis","St. Louis","New Mexico","Long Beach St","Louisville","Davidson","Murray St","Colorado St","Marquette","BYU/Iona","Florida","Virginia","Missouri","Norfolk St","Syracuse","UNC Asheville","Kansas St","Southern Miss","Vanderbilt","Harvard","Wisconsin","Montana","Cincinnati","Texas","Florida St","St. Bonaventure","Gonzaga","W Virginia","Ohio St","Loyola Md","North Carolina","Lamar/Vermont","Creighton","Alabama","Temple","Cal/USF","Michigan","Ohio","San Diego St","NC State","Georgetown","Belmont","St. Marys","Purdue","Kansas","Detroit","na","na","No Pick"]
var listOfPlayerPicks=new Array();
 
 function myPush()
 {var numtopush=this.push.arguments.length;
 var arglist=this.push.arguments;
 if(numtopush>0){for (var i=0; i<numtopush;i++)
 {this.length++;this[this.length-1]=arguments[i];}}}
 Array.prototype.push=myPush;
function getResultList(gameNum)
  {
 var tempList=new Array();
 var addToList;
var result = new Array
(0,"1","4","6","7","10","11","13","15","17","19","21","23","25","27","29","31","33","35","37","39","42","43","45","47","49","51","53","55","58","59","62","63","1","7","11","15","17","21","25","29","33","39","43","47","49","55","59","63","1","15","17","29","39","47","49","63","1","17","47","49","17","49","49","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","13","15","17","20","21","23","25","27","29","31","33","36","37","39","41","43","46","47","49","51","53","55","57","59","62","63","1","7","11","15","17","23","25","31","33","37","43","47","49","53","59","62","1","15","17","31","33","43","49","59","1","17","43","49","1","49","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","3","5","8","9","12","13","15","17","19","21","24","25","27","30","31","33","35","37","39","41","43","46","47","49","51","53","55","57","60","62","63","1","5","9","15","17","21","27","31","33","37","43","47","49","53","57","63","1","9","17","31","37","47","49","63","1","31","37","63","31","37","31","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","3","6","7","9","11","13","15","17","19","21","23","25","27","30","31","33","35","37","40","41","43","46","47","49","51","54","55","57","60","61","63","1","7","9","13","17","21","27","31","33","37","41","47","49","54","57","63","1","13","17","31","33","41","49","63","1","17","33","63","17","63","17","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","13","15","17","20","21","23","25","27","29","31","33","35","37","39","41","44","45","47","49","51","53","55","58","59","62","63","1","5","11","15","17","23","27","31","35","37","41","47","49","53","59","63","1","11","17","27","37","41","49","63","1","17","37","63","1","63","63","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","13","15","17","19","22","23","25","27","29","31","33","35","37","39","41","43","46","47","49","52","53","55","58","59","62","63","1","7","11","15","17","23","27","31","33","37","43","47","49","55","58","63","1","15","17","31","33","43","49","63","1","17","43","49","17","49","49","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","3","6","7","9","11","13","15","17","19","21","23","25","27","30","31","33","35","37","39","41","43","45","47","49","52","53","55","57","59","62","63","1","7","11","15","17","23","27","31","33","39","43","47","49","55","59","63","1","15","17","31","39","47","49","59","1","17","47","49","1","49","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","14","15","17","19","21","23","25","27","29","31","33","35","37","39","42","43","46","47","49","51","53","55","58","59","61","63","1","7","11","15","17","21","27","31","33","37","43","47","49","53","59","63","1","11","21","31","33","43","49","59","1","31","43","59","1","59","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","8","9","11","14","15","17","19","21","23","25","27","29","31","33","35","37","39","42","43","45","47","49","51","53","55","58","59","61","63","1","5","11","15","17","21","27","31","33","39","43","47","49","55","58","63","1","11","17","31","39","43","49","63","1","31","43","49","1","43","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","3","5","7","9","11","13","15","17","19","21","23","25","27","29","31","33","35","37","39","42","43","45","47","49","52","53","55","57","59","62","63","1","5","11","15","17","23","27","31","35","37","43","47","49","55","57","63","1","15","17","31","35","43","49","63","1","17","43","49","1","49","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","14","15","17","19","21","23","26","27","29","31","33","35","37","39","41","43","45","47","49","51","54","55","58","59","61","63","1","7","9","15","17","21","27","29","33","37","43","47","49","55","59","63","1","15","17","27","37","47","49","63","15","17","47","63","17","63","17","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","3","5","7","9","11","13","15","17","19","21","23","25","27","30","31","33","35","37","39","42","43","45","47","49","52","53","55","57","59","62","63","1","5","11","15","17","23","27","31","33","37","43","47","49","55","59","63","1","11","17","27","33","47","49","63","1","17","47","49","1","49","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","6","7","9","11","14","15","17","19","21","23","25","27","29","31","33","35","37","39","41","43","46","47","49","52","53","55","58","59","61","63","1","7","11","15","17","23","27","31","33","37","43","47","49","55","59","63","1","11","17","31","37","47","49","63","1","31","47","49","1","49","49","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","14","15","17","19","21","23","25","27","29","31","33","35","37","39","42","43","45","47","49","51","53","55","58","59","61","63","1","5","11","15","17","21","27","29","33","39","43","47","49","55","59","63","1","11","17","29","39","43","49","63","11","17","39","49","11","49","49","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","4","5","7","9","11","13","15","17","19","21","23","25","27","29","31","33","35","37","39","41","43","45","47","49","51","53","55","58","59","61","63","1","7","11","15","17","23","27","31","33","39","43","47","49","55","59","63","1","15","17","31","33","47","49","63","1","17","47","49","1","49","1","67","","");
addToList = tempList.push(result[gameNum]);
var result = new Array
(0,"1","3","6","7","9","11","13","15","17","19","22","23","25","27","29","31","33","35","38","39","41","43","45","47","49","51","53","55","58","59","61","63","1","7","11","15","17","23","27","31","33","39","43","47","49","55","59","63","1","15","17","31","39","43","49","63","1","17","43","49","1","49","49","67","","");
addToList = tempList.push(result[gameNum]);
listOfPlayerPicks=tempList;
 }

function openCompareList(gameNum)
 {
 var passResultNum=escape(gameNum);
document.cookie = "resultNum=" + passResultNum; 
 var url = "comparelist.html";
 var resultWindow = open(url,'ResultList','height=400,width=400,scrollbars,resizable=no,status,location=no,toolbar=no,menubar=no,directories=no');
 resultWindow.moveTo(1,1); 
 resultWindow.focus();
 }
function drawComparePicks ()
 {
 document.write("<p>");
 document.write("<b><i>Click \"Compare\" to see all player picks for that game*.</i></b><br>");
 document.write("</p>");
 document.write("<table cellpadding=0 cellspacing=0 border=0 bgcolor=\"#ffffff\"><tr><td nowrap class=\"bracketBorder\">");
 document.write("<table border=0 bgcolor=\"#ffffff\"><tr><td nowrap class=\"main\">");
 document.write("<table border=1 bgcolor=\"#ffffff\" cellspacing=0 cellpadding=0 bordercolor=\"#999999\">");
document.write("<tr><td nowrap rowspan=16 class=\"region\"></td>");
document.write("<td nowrap class=\"seed\">1</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[1]+ "<br>" + listOfTeams[2] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'1'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'33'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'49'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=16>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'57'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr><td nowrap class=\"seed\">16</td></tr>");
 document.write("<tr><td nowrap class=\"seed\">8</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[3]+ "<br>" + listOfTeams[4] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'2'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr>");
 document.write("<tr><td nowrap class=\"seed\">9</td></tr>");
 document.write("<tr><td nowrap class=\"seed\">5</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[5]+ "<br>" + listOfTeams[6] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'3'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'34'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr>");
 document.write("<tr><td nowrap class=\"seed\">12</td></tr>");
 document.write("<tr> <td nowrap class=\"seed\">4</td> ");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[7]+ "<br>" + listOfTeams[8] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'4'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr>");
 document.write("<tr> <td nowrap class=\"seed\">13</td> </tr> ");
 document.write("<tr> <td nowrap class=\"seed\">6</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[9]+ "<br>" + listOfTeams[10] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'5'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'35'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'50'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">11</td></tr><tr><td nowrap class=\"seed\">3</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[11]+ "<br>" + listOfTeams[12] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'6'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">14</td></tr><tr><td nowrap class=\"seed\">7</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[13]+ "<br>" + listOfTeams[14] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'7'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'36'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">10</td></tr><tr><td nowrap class=\"seed\">2</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[15]+ "<br>" + listOfTeams[16] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'8'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">15</td>");
 document.write("</tr><tr>");
 document.write("<TD colspan=7 bgcolor=\"#ffffff\">&nbsp;</td></tr>");
document.write("<tr><td nowrap rowspan=16 class=\"region\"></td>");
document.write("<td nowrap class=\"seed\">1</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[17]+ "<br>" + listOfTeams[18] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'9'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'37'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'51'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=16>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'58'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr><td nowrap class=\"seed\">16</td></tr>");
 document.write("<tr><td nowrap class=\"seed\">8</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[19]+ "<br>" + listOfTeams[20] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'10'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr>");
 document.write("<tr><td nowrap class=\"seed\">9</td></tr>");
 document.write("<tr><td nowrap class=\"seed\">5</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[21]+ "<br>" + listOfTeams[22] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'11'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'38'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr>");
 document.write("<tr><td nowrap class=\"seed\">12</td></tr>");
 document.write("<tr> <td nowrap class=\"seed\">4</td> ");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[23]+ "<br>" + listOfTeams[24] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'12'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr>");
 document.write("<tr> <td nowrap class=\"seed\">13</td> </tr> ");
 document.write("<tr> <td nowrap class=\"seed\">6</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[25]+ "<br>" + listOfTeams[26] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'13'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'39'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'52'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">11</td></tr><tr><td nowrap class=\"seed\">3</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[27]+ "<br>" + listOfTeams[28] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'14'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">14</td></tr><tr><td nowrap class=\"seed\">7</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[29]+ "<br>" + listOfTeams[30] + "</td>");
  document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'15'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenLt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'40'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">10</td></tr><tr><td nowrap class=\"seed\">2</td>");
 document.write("<td nowrap rowspan=2 class=\"evenLt\">" + listOfTeams[31]+ "<br>" + listOfTeams[32] + "</td>");
   document.write("<td nowrap class=\"oddLt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'16'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">15</td>");
 document.write("</tr></table></td>");
document.write("<td nowrap class=\"central\">");
 document.write("<b>Champion</b><br>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'63'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("<br><br>");
  document.write("<b>Sou/Wes Finalist</b><br>");
  document.write("<a href=\"javascript:openCompareList(");
 document.write("'61'");
 document.write(")\">");
  document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("<br><br>");
 document.write("<b>Eas/MW Finalist</b><br>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'62'");
 document.write(")\">");
  document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td>");
 document.write("<table border=1 bgcolor=\"#ffffff\" cellspacing=0 cellpadding=0 bordercolor=\"#999999\"><tr>");
  document.write("<td nowrap class=\"evenRt\" rowspan=16>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'59'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'53'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'41'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'17'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[33]+ "<br>" + listOfTeams[34] + "</td>");
 document.write("<td nowrap class=\"seed\">1</td>");
document.write("<td nowrap rowspan=16 class=\"region\"></td>");
document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">16</td></tr><tr> ");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'18'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[35]+ "<br>" + listOfTeams[36] + "</td>");
 document.write("<td nowrap class=\"seed\">8</td></tr><tr>");
 document.write("<td nowrap class=\"seed\">9</td></tr><tr>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'42'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'19'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[37]+ "<br>" + listOfTeams[38] + "</td>");
 document.write("<td nowrap class=\"seed\">5</td></tr><tr><td nowrap class=\"seed\">12</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'20'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[39]+ "<br>" + listOfTeams[40] + "</td>");
 document.write("<td nowrap class=\"seed\">4</td></tr><tr><td nowrap class=\"seed\">13</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'54'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'43'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'21'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[41]+ "<br>" + listOfTeams[42] + "</td>");
 document.write("<td nowrap class=\"seed\">6</td></tr><tr><td nowrap class=\"seed\">11</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'22'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[43]+ "<br>" + listOfTeams[44] + "</td>");
 document.write("<td nowrap class=\"seed\">3</td></tr><tr><td nowrap class=\"seed\">14</td></tr><tr>");  document.write("<td nowrap class=\"evenRt\" rowspan=4>"); document.write("<a href=\"javascript:openCompareList("); document.write("'44'"); document.write(")\">"); document.write("<b>Compare</b>"); document.write("</a>"); document.write("</td>");  document.write("<td nowrap class=\"oddRt\" rowspan=2>"); document.write("<a href=\"javascript:openCompareList("); document.write("'23'"); document.write(")\">"); document.write("<b>Compare</b>"); document.write("</a>"); document.write("</td>");  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[45]+ "<br>" + listOfTeams[46] + "</td>"); document.write("<td nowrap class=\"seed\">7</td></tr><tr><td nowrap class=\"seed\">10</td></tr><tr>");  document.write("<td nowrap class=\"oddRt\" rowspan=2>"); document.write("<a href=\"javascript:openCompareList("); document.write("'24'"); document.write(")\">"); document.write("<b>Compare</b>"); document.write("</a>"); document.write("</td>");  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[47]+ "<br>" + listOfTeams[48] + "</td>"); document.write("<td nowrap class=\"seed\">2</td></tr><tr><td nowrap class=\"seed\">15</td></tr><tr>");
 document.write("<td colspan=7 bgcolor=\"#ffffff\">&nbsp;</td></tr>");
 document.write("<tr>");
  document.write("<td nowrap class=\"evenRt\" rowspan=16>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'60'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'55'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'45'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'25'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[49]+ "<br>" + listOfTeams[50] + "</td>");
 document.write("<td nowrap class=\"seed\">1</td>");
document.write("<td nowrap rowspan=16 class=\"region\"></td>");
document.write("</tr><tr>");
 document.write("<td nowrap class=\"seed\">16</td></tr><tr> ");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'26'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[51]+ "<br>" + listOfTeams[52] + "</td>");
 document.write("<td nowrap class=\"seed\">8</td></tr><tr>");
 document.write("<td nowrap class=\"seed\">9</td></tr><tr>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'46'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'27'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[53]+ "<br>" + listOfTeams[54] + "</td>");
 document.write("<td nowrap class=\"seed\">5</td></tr><tr><td nowrap class=\"seed\">12</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'28'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[55]+ "<br>" + listOfTeams[56] + "</td>");
 document.write("<td nowrap class=\"seed\">4</td></tr><tr><td nowrap class=\"seed\">13</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=8>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'56'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'47'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'29'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[57]+ "<br>" + listOfTeams[58] + "</td>");
 document.write("<td nowrap class=\"seed\">6</td></tr><tr><td nowrap class=\"seed\">11</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'30'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[59]+ "<br>" + listOfTeams[60] + "</td>");
 document.write("<td nowrap class=\"seed\">3</td></tr><tr><td nowrap class=\"seed\">14</td></tr><tr>");
  document.write("<td nowrap class=\"evenRt\" rowspan=4>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'48'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'31'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[61]+ "<br>" + listOfTeams[62] + "</td>");
 document.write("<td nowrap class=\"seed\">7</td></tr><tr><td nowrap class=\"seed\">10</td></tr><tr>");
  document.write("<td nowrap class=\"oddRt\" rowspan=2>");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'32'");
 document.write(")\">");
 document.write("<b>Compare</b>");
 document.write("</a>");
 document.write("</td>");
  document.write("<td nowrap rowspan=2 class=\"evenRt\">" + listOfTeams[63]+ "<br>" + listOfTeams[64] + "</td>");
 document.write("<td nowrap class=\"seed\">2</td></tr><tr><td nowrap class=\"seed\">15</td></tr>");
  document.write("</table></td></tr>");
document.write("<tr><td class=\"evenLt\">Compare ");
 document.write("<a href=\"javascript:openCompareList(");
 document.write("'64'");
 document.write(")\">");
 document.write("<b>Play-in</b>");
 document.write("</a>");
 document.write("</td></tr>");
document.write("</table>");
 document.write("</td></tr>");
 document.write("</table>");
 document.write("<p>* Popup-blocking software must be disabled to view list</p>");
  }
