<?php
 $available="Yes";

$tableCount=24;

$heading = array("", "", "Rank", "&nbsp;", "Player Name", "Score", "Pick %", "Tie", "Champion", "RunnerUp", "Final 4", "Final 4", "Elite8<br>Alive", "Final4<br>Alive", "Final2<br>Alive", "Champ<br>Alive?", "Rd 1<br>Picks", "Rd 2<br>Picks", "Rd 1<br>Pts", "Rd 2<br>Pts", "Sou", "Wes", "Eas", "MW", "Upsets<br>Correct", "Bonus");

$avg = array("", "", "&nbsp;", "&nbsp;", "Pool Average", "42.4", "65.3%", "&nbsp;", "&nbsp;", "&nbsp;", "&nbsp;", "&nbsp;", "6.1", "3.5", "1.8", ".9", "21.3", "9.4", "23.4", "19", "9.4", "11", "11.5", "10.4", "2.4", "2.3");

$Player = array();
$Player[0] = array(1, "BarrieEadie-1", "1", "0","Eadie Barrie", "48", "72.3", "&nbsp;", "North Carolina", "Michigan St", "Kentucky", "Ohio St", "7", "4", "2", "Yes", "24", "10", "28", "20", "13", "10", "13", "12", "5", "4");
$Player[1] = array(2, "EickhoffEric-1", "2t", "+13","Eric Eickhoff", "46", "66", "&nbsp;", "North Carolina", "Michigan St", "Kentucky", "Florida St", "6", "4", "2", "Yes", "20", "11", "22", "24", "9", "11", "11", "15", "3", "4");
$Player[2] = array(3, "GrantEarl-1", "2t", "0","Earl Grant", "46", "70.2", "&nbsp;", "Kentucky", "North Carolina", "Michigan St", "Ohio St", "5", "4", "2", "Yes", "22", "11", "24", "22", "12", "11", "14", "9", "2", "2");
$Player[3] = array(4, "SobiskiKevin2", "2t", "+7","Kevin Sobiski #2", "46", "70.2", "&nbsp;", "North Carolina", "Kentucky", "Michigan St", "Florida St", "6", "4", "2", "Yes", "22", "11", "24", "22", "12", "11", "13", "10", "2", "2");
$Player[4] = array(5, "HohnbaumKevin-1", "5t", "+7","Kevin Hohnbaum", "45", "66", "&nbsp;", "Kentucky", "Florida St", "Missouri", "North Carolina", "7", "3", "2", "Yes", "21", "10", "23", "22", "8", "10", "13", "14", "3", "4");
$Player[5] = array(6, "MccoyJoseph-1", "5t", "+1","Joseph Mccoy", "45", "68.1", "&nbsp;", "North Carolina", "Kentucky", "Missouri", "Ohio St", "6", "3", "2", "Yes", "22", "10", "25", "20", "13", "12", "11", "9", "3", "3");
$Player[6] = array(7, "SobiskiKevin-1", "5t", "+7","Kevin Sobiski", "45", "70.2", "&nbsp;", "Kentucky", "North Carolina", "Michigan St", "Ohio St", "6", "4", "2", "Yes", "22", "11", "23", "22", "9", "12", "14", "10", "1", "1");
$Player[7] = array(8, "MannellaJeanne-1", "8t", "-5","Jeanne Mannella", "44", "68.1", "&nbsp;", "Michigan St", "Kansas", "Duke", "Ohio St", "6", "3", "2", "Yes", "23", "9", "26", "18", "9", "11", "12", "12", "4", "3");
$Player[8] = array(9, "PovlinskiBryan-1", "8t", "+1","Bryan Povlinski", "44", "68.1", "&nbsp;", "North Carolina", "Baylor", "Michigan St", "Wisconsin", "8", "4", "2", "Yes", "22", "10", "24", "20", "9", "12", "13", "10", "3", "2");
$Player[9] = array(10, "BurchamRodger3", "10", "-7","Rodger Burcham #3", "42", "66", "&nbsp;", "Kansas", "Kentucky", "Michigan St", "Vanderbilt", "7", "3", "2", "Yes", "23", "8", "26", "16", "7", "14", "9", "12", "3", "3");
$Player[10] = array(11, "GrantErin-1", "11", "+1","Erin Grant", "41", "63.8", "&nbsp;", "Kentucky", "Georgetown", "Missouri", "Florida St", "5", "2", "1", "Yes", "21", "9", "23", "18", "11", "10", "10", "10", "2", "2");
$Player[11] = array(12, "BrooksBilly-1", "12t", "-9","Billy Brooks", "39", "61.7", "&nbsp;", "Kentucky", "North Carolina", "Michigan St", "Florida St", "5", "4", "2", "Yes", "21", "8", "23", "16", "9", "12", "10", "8", "2", "2");
$Player[12] = array(13, "MannellaJeanne2", "12t", "-3","Jeanne Mannella #2", "39", "61.7", "&nbsp;", "Kentucky", "North Carolina", "Michigan St", "Ohio St", "8", "4", "2", "Yes", "20", "9", "21", "18", "8", "11", "11", "9", "1", "1");
$Player[13] = array(14, "BurchamRodger2", "14t", "-8","Rodger Burcham #2", "38", "59.6", "&nbsp;", "Michigan St", "Kansas", "Kentucky", "Syracuse", "6", "4", "2", "Yes", "20", "8", "22", "16", "10", "9", "10", "9", "2", "2");
$Player[14] = array(15, "HopperAnita-1", "14t", "-8","Anita Hopper", "38", "61.7", "&nbsp;", "Kentucky", "North Carolina", "Michigan St", "Florida St", "5", "4", "2", "Yes", "21", "8", "22", "16", "8", "12", "9", "9", "1", "1");
$Player[15] = array(16, "BurchamRodger-1", "16", "0","Rodger Burcham", "32", "51.1", "&nbsp;", "Missouri", "Vanderbilt", "Kentucky", "Kansas", "5", "2", "0", "No", "17", "7", "18", "14", "4", "8", "11", "9", "1", "1");

$standingsOK="Yes";
 ?>
